profilev2 misc sync and fixes [SQUASHME?] (#149)
* drop cachetools as its memory caching and can delete objects

* pin python-jose* to 3.0.0 as 3.0.1 has an issue:
`E       AttributeError: 'RSAKey' object has no attribute 'to_dict'`

* Add test targets to validate profiles are json
Allow null identity value for empty profiles
Add demo null profile which has no values with dates set to the epoch as
it's a useful starting point for empty/skeleton extended profiles

* load new schema version
load new null profile based on new schema version
use a centralized null profile from cis profile_data docs as local
cached copy

* pinning typo

* de-pin python-jose as its not actually the issue
the install order is:
- some programs dont understand the notation
`python-jose[extrafeaturehere]`
- you can use `python-jose-extrafeaturehere` instead
- when you do that, in certain cases it tries to detect installation of
the parent package during its own installation, so the order matters

tldr change order to install python-jose-cryptodome first ensures that
python-jose will detect it and change how it installs itself

* Add watch-test target which runs ptw, but runs the full test suite incl.
flake
Fix flake8 test req

* spaces=>tabs in makefiles

* Fix test install for local tests, with install cache

* correct import relative path
remove copyright and version info as its present in setup.py (easier
maintenance)

* support installation of local npm modules for local dev envs

* ensure processes are killed no matter how the test class is called by
binding teardown() to __delete__() builtin

* fix relative imports

* fix flake8, drop x5t

* fix relative imports

* add new common imports

* fix relative imports

* fix relative imports

* fix relative imports
fix deps
add flake8 setup

* fix relative imports
add makefile

* add common to fix relative import